#### Importar librerias

In [14]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent / 'src'))

In [15]:
from utils import extract_clean_ticker,añadir_indicadores_tecnicos


[enlace a Documentacion libreria TA]: https://technical-analysis-library-in-python.readthedocs.io/en/latest/ta.html
[**Visita la documentación libreria TA** ][enlace a Documentacion libreria TA]

#### Extraccion de datos OHLCV (Open,High,Low,Close,Volume) del ticket definido 
- Elegimos Tickets
- Funcion extract_clean_ticker() para crear el dataset inicial y tener los datos historicos.

In [16]:
# Definimos los tickets 
vandguard_sp500 = 'VOO'

In [17]:

df_voo = extract_clean_ticker(vandguard_sp500, start='2010-01-01', end='2025-06-01', interval='1d')

df_voo['date'] = pd.to_datetime(df_voo['date'])

#### Agregar indicadores tecnicos al dataframe

In [18]:
df_voo = añadir_indicadores_tecnicos(df_voo)

In [19]:

df_voo.to_csv('../data/VOO.csv', index=False)

In [20]:
df_voo.head()

,date,close,high,low,open,volume,daily_return,rsi,macd,macd_signal,...,ema_200,ema_9,ichimoku_a,ichimoku_b,ichimoku_base,ichimoku_conversion,adx,volume_sma_20,volume_ratio,awesome_osc
0,2011-06-23,91.127,91.158,89.689,90.338,260750,-0.003,44.614,-0.773,-0.887,...,89.286,91.098,91.583,93.16,92.395,90.771,21.805,116412.5,2.240,-2.011
1,2011-06-24,90.125,91.181,89.969,91.150,114500,-0.011,39.853,-0.802,-0.870,...,89.295,90.904,91.583,93.16,92.395,90.771,21.981,119115.0,0.961,-1.842
2,2011-06-27,90.886,91.228,89.985,90.187,77850,0.008,44.681,-0.756,-0.847,...,89.310,90.900,91.564,93.16,92.356,90.771,22.092,120627.5,0.645,-1.670
3,2011-06-28,92.051,92.082,91.181,91.274,59500,0.013,51.147,-0.618,-0.801,...,89.338,91.130,91.564,93.16,92.356,90.771,21.284,114977.5,0.517,-1.543
4,2011-06-29,92.875,92.999,92.191,92.533,125350,0.009,55.141,-0.436,-0.728,...,89.373,91.479,91.850,93.16,92.356,91.344,19.838,110145.0,1.138,-1.305

In [21]:
print("Información del DataFrame:")
df_voo.info()
print("Resumen Estadístico:")
display(df_voo.describe().T)

Información del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3505 entries, 0 to 3504
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 3505 non-null   datetime64[ns]
 1   close                3505 non-null   float64
 2   high                 3505 non-null   float64
 3   low                  3505 non-null   float64
 4   open                 3505 non-null   float64
 5   volume               3505 non-null   int64
 6   daily_return         3505 non-null   float64
 7   rsi                  3505 non-null   float64
 8   macd                 3505 non-null   float64
 9   macd_signal          3505 non-null   float64
 10  macd_diff            3505 non-null   float64
 11  stochastic_k         3505 non-null   float64
 12  stochastic_d         3505 non-null   float64
 13  bollinger_hband      3505 non-null   float64
 14  bollinger_lband      3505 non-null   float64
 15  bollinger_mavg       3505 non-null   float64
 16  bollinger_width      3505 non-null   float64
 17  atr                  3505 non-null   float64
 18  ema_20               3505 non-null   float64
 19  ema_50               3505 non-null   float64
 20  ema_200              3505 non-null   float64
 21  ema_9                3505 non-null   float64
 22  ichimoku_a           3505 non-null   float64
 23  ichimoku_b           3505 non-null   float64
 24  ichimoku_base        3505 non-null   float64
 25  ichimoku_conversion  3505 non-null   float64
 26  adx                  3505 non-null   float64
 27  volume_sma_20        3505 non-null   float64
 28  volume_ratio         3505 non-null   float64
 29  awesome_osc          3505 non-null   float64
dtypes: datetime64[ns](1), float64(28), int64(1)
memory usage: 821.6 KB
Resumen Estadístico:

,count,mean,min,25%,50%,75%,max,std
date,3505,2018-06-10 05:22:55.292439296,2011-06-23 00:00:00,2014-12-16 00:00:00,2018-06-11 00:00:00,2021-12-01 00:00:00,2025-05-30 00:00:00,NaN
close,3505.0,250.392799,78.396,151.198,220.594,354.901,559.994,125.701191
high,3505.0,251.677629,80.333,151.974,222.178,356.73,560.242,126.400327
low,3505.0,248.900966,76.755,150.553,218.967,352.131,556.874,124.888432
open,3505.0,250.354551,77.458,151.26,220.542,354.617,558.722,125.67805
volume,3505.0,3055023.908702,40350.0,1286900.0,2507800.0,4055000.0,35418000.0,2787266.705416
daily_return,3505.0,0.000571,-0.117,-0.004,0.001,0.006,0.095,0.011073
rsi,3505.0,56.109111,16.747,48.15,57.492,64.535,87.268,11.361659
macd,3505.0,0.855424,-19.894,-0.155,1.007,2.218,11.28,2.989975
macd_signal,3505.0,0.844326,-16.631,-0.093,0.97,2.161,8.944,2.77118
macd_diff,3505.0,0.011092,-5.846,-0.295,0.02,0.363,5.169,0.976395
stochastic_k,3505.0,65.481508,0.0,42.522,74.937,92.312,100.0,30.390014
stochastic_d,3505.0,65.477687,0.482,43.338,75.266,90.185,99.868,28.030482
bollinger_hband,3505.0,257.097986,87.183,155.212,228.932,366.069,571.523,129.531165
bollinger_lband,3505.0,241.269936,76.592,145.794,212.022,337.823,545.836,120.633019
bollinger_mavg,3505.0,249.183951,82.994,150.949,220.335,352.508,553.097,124.96991
bollinger_width,3505.0,6.144829,0.94,3.71,5.195,7.349,43.187,4.054852
atr,3505.0,3.150977,0.756,1.309,2.23,4.294,18.09,2.397294
ema_20,3505.0,249.202402,82.62,151.158,220.747,354.006,552.792,124.955943
ema_50,3505.0,247.388954,84.677,151.693,219.79,352.222,547.324,123.915544
ema_200,3505.0,238.272119,87.601,147.372,213.725,352.262,518.212,118.075493
ema_9,3505.0,249.883012,81.487,151.265,220.651,354.033,555.907,125.36507
ichimoku_a,3505.0,248.392353,81.52,150.281,219.238,353.148,551.378,124.46347
ichimoku_b,3505.0,245.297385,82.458,149.137,217.781,348.92,542.906,122.883636
ichimoku_base,3505.0,247.485333,81.94,150.188,218.209,352.11,549.84,123.944049
ichimoku_conversion,3505.0,249.299387,81.068,150.824,220.539,353.895,553.521,125.037512
adx,3505.0,22.67753,8.301,16.649,21.084,27.458,55.067,8.043138
volume_sma_20,3505.0,3038649.605563,98840.0,1485045.0,2592215.0,4134465.0,13857320.0,2208117.126678
volume_ratio,3505.0,1.023932,0.186,0.706,0.909,1.198,5.441,0.519521
awesome_osc,3505.0,1.796136,-53.252,-0.84,2.203,5.461,36.617,7.848154

In [22]:

print("2. Análisis de Series Temporales")
fig_price_volume = make_subplots(rows=2, cols=1, shared_xaxes=True,vertical_spacing=0.1, row_heights=[0.7, 0.3])

# Gráfico de Precios con Medias Móviles
fig_price_volume.add_trace(go.Scatter(x=df_voo['date'], y=df_voo['close'], name='Precio de Cierre', line=dict(color='black')), row=1, col=1)
fig_price_volume.add_trace(go.Scatter(x=df_voo['date'], y=df_voo['ema_20'], name='EMA 20 días', line=dict(color='orange', dash='dash')), row=1, col=1)
fig_price_volume.add_trace(go.Scatter(x=df_voo['date'], y=df_voo['ema_50'], name='EMA 50 días', line=dict(color='red', dash='dash')), row=1, col=1)

# Gráfico de Volumen
fig_price_volume.add_trace(go.Bar(x=df_voo['date'], y=df_voo['volume'], name='Volumen', marker_color='gray'), row=2, col=1)

fig_price_volume.update_layout(title_text='Análisis de Precio y Volumen', legend_title_text='Leyenda')
fig_price_volume.update_yaxes(title_text="Precio ($)", row=1, col=1)
fig_price_volume.update_yaxes(title_text="Volumen", row=2, col=1)
fig_price_volume.show()

2. Análisis de Series Temporales

In [23]:
# Análisis de Distribución y Volatilidad
print("\n3. Análisis de Distribución y Volatilidad")
df_voo['daily_return'] = df_voo['close'].pct_change()

# Histograma de los retornos diarios
fig_hist = px.histogram(df_voo.dropna(), x='daily_return', nbins=100,title='Distribución de los Retornos Diarios', labels={'daily_return': 'Retorno Diario'})
fig_hist.show()

# Gráfico de Volatilidad Móvil
fig_vol = px.line(df_voo, x='date', y='atr',title='Volatilidad del Mercado (ATR 14 días)', labels={'atr': 'Average True Range'})
fig_vol.show()

3. Análisis de Distribución y Volatilidad

In [24]:
print("\nAnálisis de Caídas Máximas (Drawdown)")

# Calculo de rendimientos acumulados 
df_voo['cumulative_return'] = (1 + df_voo['daily_return']).cumprod()

# Calcula el maximo historico
df_voo['running_max'] = df_voo['cumulative_return'].cummax()

# calcula las mayores caidas del activo 
df_voo['drawdown'] = (df_voo['cumulative_return'] - df_voo['running_max']) /df_voo['running_max']

#Visualizar eel drawdonw

fig_drawdown = go.Figure()
fig_drawdown.add_trace(go.Scatter(
    x=df_voo['date'], y=df_voo['drawdown'], 
    fill='tozeroy', fillcolor='rgba(255, 0, 0, 0.3)',
    line_color='red', name='Drawdown'))

fig_drawdown.update_layout(title='Análisis de Caídas Máximas (Drawdown) del Activo',yaxis_title='Caída desde el Máximo (%)')
fig_drawdown.show()

Análisis de Caídas Máximas (Drawdown)