In [21]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent / 'src'))

In [22]:
import pandas as pd
import numpy as np
# Funciones para crear señales 
from utils import ema_price_signal, macd_signal, stochastic_oversold_signal, ichimoku_buy_signals, ichimoku_signal_aggressive, ichimoku_signal_kijun_cross, ichimoku_signal_chikou_break, bollinger_reversion_signal
from utils import create_combined_signal, generar_estrategias_combinadas
# Funciones para backtesting
from utils import backtest_dca_pure,backtest_dca_plus_trading_WITH_SL,backtest_dca_plus_trading_NO_SL,backtest_with_atr_SL,evaluate_all_strategies
#Funcion para crear Target
from utils import crear_target

In [23]:
df = pd.read_csv('../data/VOO.csv')

In [24]:
df.head(3)

,date,close,high,low,open,volume,daily_return,rsi,macd,macd_signal,...,ema_200,ema_9,ichimoku_a,ichimoku_b,ichimoku_base,ichimoku_conversion,adx,volume_sma_20,volume_ratio,awesome_osc
0,2011-06-23,91.127,91.158,89.689,90.338,260750,-0.003,44.614,-0.773,-0.887,...,89.286,91.098,91.583,93.16,92.395,90.771,21.805,116412.5,2.240,-2.011
1,2011-06-24,90.125,91.181,89.969,91.150,114500,-0.011,39.853,-0.802,-0.870,...,89.295,90.904,91.583,93.16,92.395,90.771,21.981,119115.0,0.961,-1.842
2,2011-06-27,90.886,91.228,89.985,90.187,77850,0.008,44.681,-0.756,-0.847,...,89.310,90.900,91.564,93.16,92.356,90.771,22.092,120627.5,0.645,-1.670

In [25]:
df['date'] = pd.to_datetime(df['date'])

### SEÑALES

In [26]:
df = ema_price_signal(df)
df = macd_signal(df)
df = stochastic_oversold_signal(df)
df = ichimoku_buy_signals(df)
df = ichimoku_signal_aggressive(df)
df = ichimoku_signal_kijun_cross(df)
df = ichimoku_signal_chikou_break(df)
df = bollinger_reversion_signal(df)

In [27]:
combinaciones = [
    ('signal_macd_buy', 'signal_stochastic_buy'),
    ('signal_ema_price', 'signal_macd_buy'),
    ('signal_ichimoku_kijun_cross', 'signal_stochastic_buy'),
    ('signal_ema_price', 'signal_stochastic_buy')]

df, nuevas_estrategias = generar_estrategias_combinadas(df, combinaciones)

 Creando Estrategias Combinadas
Señal combinada 'signal_macd_&_stochastic' creada.
Señal combinada 'signal_ema_price_&_macd' creada.
Señal combinada 'signal_ichimoku_kijun_cross_&_stochastic' creada.
Señal combinada 'signal_ema_price_&_stochastic' creada.
Se han añadido las siguientes columnas de señales combinadas al dataframe:
- signal_macd_&_stochastic
- signal_ema_price_&_macd
- signal_ichimoku_kijun_cross_&_stochastic
- signal_ema_price_&_stochastic

### Backtest

In [28]:
#Parametros para los backtests 

estrategias_a_probar = [
    # Individuales
    'signal_ema_price',
    'signal_macd_buy',
    'signal_stochastic_buy',
    'signal_ichimoku_kijun_cross',
    'signal_bollinger_buy',
    
    # Combinadas
    'signal_macd_&_stochastic',
    'signal_ema_price_&_macd',
    'signal_ichimoku_kijun_cross_&_stochastic',
    'signal_ema_price_&_stochastic'    
]

params = {
    'monthly_invest': 400,
    'trade_amount': 150,
    'take_profit_pct': 0.125,
    'initial_trading_cash': 1000,
    'verbose': False 
}

params_atr = {
    'monthly_invest': 400,
    'trade_amount': 150,
    'atr_multiplier_tp': 10.0,   
    'atr_multiplier_sl': 3.0,  
    'initial_trading_cash': 1000,
    'verbose': False
}

#### Backtest solo DCA

In [29]:
resultados_dca, df_dca = backtest_dca_pure(df, monthly_invest=400)

 Resultados para la estrategia: DCA Puro
Valor Final del Portafolio: $188,975.89
Ganancia/Pérdida Absoluta: $121,775.89
Total Aportado: $67,200.00
Retorno Porcentual: 181.21%

#### Backtest DCA + Señales de compra con StopLoss SIN ATR

In [30]:
print(" Iniciando Evaluación con Stops sin ATR")
df_resultados_finales = evaluate_all_strategies(df, estrategias_a_probar, backtest_dca_plus_trading_WITH_SL,params)

print("\n Tabla Comparativa de Estrategias")
display(df_resultados_finales)

 Iniciando Evaluación con Stops sin ATR
Evaluando: signal_ema_price...
Evaluando: signal_macd_buy...
Evaluando: signal_stochastic_buy...
Evaluando: signal_ichimoku_kijun_cross...
Evaluando: signal_bollinger_buy...
Evaluando: signal_macd_&_stochastic...
Evaluando: signal_ema_price_&_macd...
Evaluando: signal_ichimoku_kijun_cross_&_stochastic...
Evaluando: signal_ema_price_&_stochastic...

 Tabla Comparativa de Estrategias

,Strategy,Final Portfolio Value,Total Contributions,Absolute Return,Percentage Return,Trading PnL,Trading Capital Used,Open Trades at End,Value of Open Trades,Sharpe Ratio,Total DCA Shares
0,signal_ichimoku_kijun_cross (With SL),190878.361100,68200,122678.361100,179.880295,871.666520,21000,2,330.806686,1.610877,349.895088
1,signal_macd_buy (With SL),190213.104264,68200,122013.104264,178.904845,237.216369,4500,0,0.000000,1.615794,349.895088
2,signal_ema_price (With SL),190036.662987,68200,121836.662987,178.646133,60.775092,3750,0,0.000000,1.613708,349.895088
3,signal_stochastic_buy (With SL),190021.980565,68200,121821.980565,178.624605,46.092671,3150,0,0.000000,1.614906,349.895088
4,signal_ema_price_&_macd (With SL),190013.813044,68200,121813.813044,178.612629,37.925150,300,0,0.000000,1.615953,349.895088
5,signal_ichimoku_kijun_cross_&_stochastic (With...,190006.820955,68200,121806.820955,178.602377,30.933061,1800,0,0.000000,1.615170,349.895088
6,signal_bollinger_buy (With SL),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.000000,1.615625,349.895088
7,signal_macd_&_stochastic (With SL),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.000000,1.615625,349.895088
8,signal_ema_price_&_stochastic (With SL),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.000000,1.615625,349.895088

#### Backtest DCA + Señales de compra con StopLoss CON ATR

In [31]:

df_results_atr = evaluate_all_strategies(df, estrategias_a_probar,  backtest_with_atr_SL, params_atr)
print("\n Tabla Comparativa con Stops con ATR ")
display(df_results_atr)

Evaluando: signal_ema_price...
Evaluando: signal_macd_buy...
Evaluando: signal_stochastic_buy...
Evaluando: signal_ichimoku_kijun_cross...
Evaluando: signal_bollinger_buy...
Evaluando: signal_macd_&_stochastic...
Evaluando: signal_ema_price_&_macd...
Evaluando: signal_ichimoku_kijun_cross_&_stochastic...
Evaluando: signal_ema_price_&_stochastic...

 Tabla Comparativa con Stops con ATR

,Strategy,Final Portfolio Value,Total Contributions,Absolute Return,Percentage Return,Trading PnL,Trading Capital Used,Open Trades at End,Value of Open Trades,Sharpe Ratio,Total DCA Shares
0,signal_ichimoku_kijun_cross (ATR Stops),190767.970709,68200,122567.970709,179.718432,748.454965,20850,3,493.62785,1.609683,349.895088
1,signal_ema_price (ATR Stops),190235.890028,68200,122035.890028,178.938255,260.002134,3750,0,0.00000,1.614822,349.895088
2,signal_macd_buy (ATR Stops),190157.314581,68200,121957.314581,178.823042,181.426687,4500,0,0.00000,1.615243,349.895088
3,signal_ema_price_&_macd (ATR Stops),190009.792521,68200,121809.792521,178.606734,33.904627,300,0,0.00000,1.615943,349.895088
4,signal_stochastic_buy (ATR Stops),190006.993567,68200,121806.993567,178.602630,31.105673,3150,0,0.00000,1.614820,349.895088
5,signal_bollinger_buy (ATR Stops),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.00000,1.615625,349.895088
6,signal_macd_&_stochastic (ATR Stops),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.00000,1.615625,349.895088
7,signal_ema_price_&_stochastic (ATR Stops),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.00000,1.615625,349.895088
8,signal_ichimoku_kijun_cross_&_stochastic (ATR ...,189934.907337,68200,121734.907337,178.496932,-40.980557,1800,0,0.00000,1.614711,349.895088

#### Backtest DCA + Señales de compra sin StopLoss ni ATR

In [32]:

df_resultados_finales = evaluate_all_strategies(df, estrategias_a_probar, backtest_dca_plus_trading_NO_SL,params)


print("\n Tabla Comparativa de Estrategias sin Stop ")
display(df_resultados_finales)

Evaluando: signal_ema_price...
Evaluando: signal_macd_buy...
Evaluando: signal_stochastic_buy...
Evaluando: signal_ichimoku_kijun_cross...
Evaluando: signal_bollinger_buy...
Evaluando: signal_macd_&_stochastic...
Evaluando: signal_ema_price_&_macd...
Evaluando: signal_ichimoku_kijun_cross_&_stochastic...
Evaluando: signal_ema_price_&_stochastic...

 Tabla Comparativa de Estrategias sin Stop

,Strategy,Final Portfolio Value,Total Contributions,Absolute Return,Percentage Return,Trading PnL,Trading Capital Used,Open Trades at End,Value of Open Trades,Sharpe Ratio,Total DCA Shares
0,signal_ichimoku_kijun_cross (No SL),192076.554544,68200,123876.554544,181.637177,2044.182605,17100,8,1256.484045,1.607162,349.895088
1,signal_macd_buy (No SL),190473.560822,68200,122273.560822,179.286746,499.262025,4050,1,148.410903,1.615560,349.895088
2,signal_ema_price (No SL),190437.668002,68200,122237.668002,179.234117,457.742742,3750,1,154.037366,1.616138,349.895088
3,signal_stochastic_buy (No SL),190378.688938,68200,122178.688938,179.147638,402.801044,3150,0,0.000000,1.615539,349.895088
4,signal_ichimoku_kijun_cross_&_stochastic (No SL),190208.506204,68200,122008.506204,178.898103,232.618309,1800,0,0.000000,1.615423,349.895088
5,signal_ema_price_&_macd (No SL),190013.813044,68200,121813.813044,178.612629,37.925150,300,0,0.000000,1.615953,349.895088
6,signal_bollinger_buy (No SL),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.000000,1.615625,349.895088
7,signal_macd_&_stochastic (No SL),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.000000,1.615625,349.895088
8,signal_ema_price_&_stochastic (No SL),189975.887894,68200,121775.887894,178.557020,0.000000,0,0,0.000000,1.615625,349.895088


### Hipótesis 1: Sobre la Viabilidad de la Inversión Activa VS Pasiva


**Hipótesis Nula (H₀)**: Una estrategia de inversión activa, que combina DCA con trading, no genera un rendimiento superior al de una estrategia puramente pasiva de aportaciones periódicas (DCA Puro).

**Hipótesis Alternativa (H₁)**: Una estrategia de inversión activa bien diseñada sí puede generar un rendimiento superior al de la estrategia pasiva, superando el "coste de oportunidad".

- Generando una estrategia de solo DCA (inversion pasiva, comprar y mantener) se genera un retorno del 181,20% mientras que con una estrategia activa (Combinacion de DCA con trades) se genera 181.63% ligeramente superior.

### Hipótesis 2: Sobre la Efectividad de los Tipos de Indicadores 

Hipótesis Nula (H₀): No existe una diferencia significativa en el rendimiento entre las estrategias basadas en seguimiento de tendencia (MACD), las de reversión a la media (Estocástico) o las de equilibrio (Ichimoku).

Hipótesis Alternativa (H₁): Para un activo con fuerte tendencia como VOO, las estrategias basadas en equilibrio y tendencia son significativamente más rentables que las de reversión.

- Utilizando estrategias basadas en compra activa segun las señales de indicadores tecnicos, si exixte unas diferences significativas entre las de reversion y las de equilibrio y tendencia.
- Utilizando Ichimoku vemos como el capital que se invierte en un primer momento (capital inicial = 1000$) al final del ciclo es recuperado ademas de doblado y representando un 12% del capital reinvertido en el periodo estudiado.

### Hipótesis 3: Sobre la Gestión del Riesgo (El Impacto del Stop-Loss) 

Esta hipótesis se centra en cómo la gestión de riesgo afecta los resultados en un mercado específico.

Hipótesis Nula (H₀): La implementación de un stop-loss mejora o no afecta negativamente el rendimiento total al limitar las pérdidas.

Hipótesis Alternativa (H₁): En un mercado fuertemente alcista, la eliminación del stop-loss mejora el rendimiento total, ya que evita la venta prematura en caídas temporales.

- la estrategia con mejor PNL y mejores resultados absolutos es aquella en la que utilizamos ichimoku sin el stop loss lo que hace que se rechaze la hipotesis nula de que el stop loss mejora el rendimiento.

In [33]:
# Aplicar la función para crear un target viable: aqui dejamos un target en el que le indicamos si el precio sube un 4% en 19 dias. 
df = crear_target(df, dias_futuro=19, umbral_retorno=0.04)

In [34]:
df.head()

,date,close,high,low,open,volume,daily_return,rsi,macd,macd_signal,...,signal_ichimoku_aggressive,signal_ichimoku_kijun_cross,signal_ichimoku_chikou,signal_bollinger_buy,signal_macd_&_stochastic,signal_ema_price_&_macd,signal_ichimoku_kijun_cross_&_stochastic,signal_ema_price_&_stochastic,retorno_futuro,target
0,2011-06-23,91.127,91.158,89.689,90.338,260750,-0.003,44.614,-0.773,-0.887,...,False,False,False,False,False,False,False,False,0.048679,1
1,2011-06-24,90.125,91.181,89.969,91.150,114500,-0.011,39.853,-0.802,-0.870,...,False,False,False,False,False,False,False,False,0.061204,1
2,2011-06-27,90.886,91.228,89.985,90.187,77850,0.008,44.681,-0.756,-0.847,...,False,False,False,False,False,False,False,False,0.046333,1
3,2011-06-28,92.051,92.082,91.181,91.274,59500,0.013,51.147,-0.618,-0.801,...,False,False,False,False,False,False,False,False,0.028701,0
4,2011-06-29,92.875,92.999,92.191,92.533,125350,0.009,55.141,-0.436,-0.728,...,False,True,False,False,False,False,False,False,-0.000668,0

In [35]:
# Creación de Características Numéricas Avanzadas 
df['body_size'] = abs(df['close'] - df['open'])
df['upper_wick'] = df['high'] - df[['open', 'close']].max(axis=1)
df['lower_wick'] = df[['open', 'close']].min(axis=1) - df['low']

# Calcula el ROC, que mide el cambio porcentual del activo a lo larco del tiempo 
df['rsi_roc_5'] = df['rsi'].pct_change(periods=5) * 100

# Características Cíclicas del Tiempo
df['month_sin'] = np.sin(2 * np.pi * df['date'].dt.month / 12)
df['month_cos'] = np.cos(2 * np.pi * df['date'].dt.month / 12)

# Esto crea los cruces entre el precio, kinun y tenkan 
df['price_vs_kijun'] = df['close'] - df['ichimoku_base']
df['tenkan_vs_kijun'] = df['ichimoku_conversion'] - df['ichimoku_base']

# Limpiar los NaNs generados por los nuevos cálculos
df = df.dropna()

In [36]:
#exportamos los datos a un csv en la carpeta data
df.to_csv('../data/VOO_ind_signal.csv', index=False)