In [1]:
import sys
import pandas as pd
from pathlib import Path

sys.path.append(str(Path().resolve().parent / 'src'))
from utils import backtest_dca_pure, evaluate_all_strategies, backtest_dca_plus_trading_WITH_SL, backtest_with_atr_SL, backtest_dca_plus_trading_NO_SL, backtest_dca_self_sufficient

In [2]:
df = pd.read_csv('../data/VOO_ind_signal.csv')

In [3]:
#Parametros para los backtests 

estrategias_a_probar = [
    # Individuales
    'signal_ema_price',
    'signal_macd_buy',
    'signal_stochastic_buy',
    'signal_ichimoku_kijun_cross',
    'signal_bollinger_buy',
    
    # Combinadas
    'signal_macd_&_stochastic',
    'signal_ema_price_&_macd',
    'signal_ichimoku_kijun_cross_&_stochastic',
    'signal_ema_price_&_stochastic'    
]

params = {
    'monthly_invest': 400,
    'trade_amount': 150,
    'take_profit_pct': 0.125,
    'initial_trading_cash': 1000,
    'verbose': False 
}

params_atr = {
    'monthly_invest': 400,
    'trade_amount': 150,
    'atr_multiplier_tp': 10.0,   
    'atr_multiplier_sl': 3.0,  
    'initial_trading_cash': 1000,
    'verbose': False
}

### 1.Backtesting inicial antes del entrenamiento de modelos.

#### 1.1 Backtesting estrategia Dollar Cost Average (DCA)

In [4]:
resultados_dca, df_dca = backtest_dca_pure(df, monthly_invest=400)

 Resultados para la estrategia: DCA Puro
Valor Final del Portafolio: $181,568.96
Ganancia/Pérdida Absoluta: $114,368.96
Total Aportado: $67,200.00
Retorno Porcentual: 170.19%

#### 1.2 Backtesting con Stop Loss Fijos

In [5]:
print(" Iniciando Evaluación con Stops sin ATR")
df_resultados_finales = evaluate_all_strategies(df, estrategias_a_probar, backtest_dca_plus_trading_WITH_SL, params)

print("\n Tabla Comparativa de Estrategias")
display(df_resultados_finales)

 Iniciando Evaluación con Stops sin ATR
Evaluando: signal_ema_price...
Evaluando: signal_macd_buy...
Evaluando: signal_stochastic_buy...
Evaluando: signal_ichimoku_kijun_cross...
Evaluando: signal_bollinger_buy...
Evaluando: signal_macd_&_stochastic...
Evaluando: signal_ema_price_&_macd...
Evaluando: signal_ichimoku_kijun_cross_&_stochastic...
Evaluando: signal_ema_price_&_stochastic...

 Tabla Comparativa de Estrategias

,Strategy,Final Portfolio Value,Total Contributions,Absolute Return,Percentage Return,Trading PnL,Trading Capital Used,Open Trades at End,Value of Open Trades,Sharpe Ratio,Total DCA Shares
0,signal_ichimoku_kijun_cross (With SL),183470.526,68200,115270.526,169.018,883.613,20850,2,317.953,1.606,349.772
1,signal_macd_buy (With SL),182806.176,68200,114606.176,168.044,237.216,4500,0,0.000,1.608,349.772
2,signal_ema_price (With SL),182629.735,68200,114429.735,167.786,60.775,3750,0,0.000,1.606,349.772
3,signal_stochastic_buy (With SL),182615.053,68200,114415.053,167.764,46.093,3150,0,0.000,1.607,349.772
4,signal_ema_price_&_macd (With SL),182606.885,68200,114406.885,167.752,37.925,300,0,0.000,1.608,349.772
5,signal_ichimoku_kijun_cross_&_stochastic (With...,182599.893,68200,114399.893,167.742,30.933,1800,0,0.000,1.607,349.772
6,signal_bollinger_buy (With SL),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772
7,signal_macd_&_stochastic (With SL),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772
8,signal_ema_price_&_stochastic (With SL),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772

#### 1.3 Backtesting de incluyendo StopLoss dinamicos combinado con ATR

In [6]:
print(" Iniciando Evaluación con Stops con ATR")

df_results_atr = evaluate_all_strategies(df, estrategias_a_probar,  backtest_with_atr_SL, params_atr)
print("\n Tabla Comparativa con Stops con ATR ")
display(df_results_atr)

 Iniciando Evaluación con Stops con ATR
Evaluando: signal_ema_price...
Evaluando: signal_macd_buy...
Evaluando: signal_stochastic_buy...
Evaluando: signal_ichimoku_kijun_cross...
Evaluando: signal_bollinger_buy...
Evaluando: signal_macd_&_stochastic...
Evaluando: signal_ema_price_&_macd...
Evaluando: signal_ichimoku_kijun_cross_&_stochastic...
Evaluando: signal_ema_price_&_stochastic...

 Tabla Comparativa con Stops con ATR

,Strategy,Final Portfolio Value,Total Contributions,Absolute Return,Percentage Return,Trading PnL,Trading Capital Used,Open Trades at End,Value of Open Trades,Sharpe Ratio,Total DCA Shares
0,signal_ichimoku_kijun_cross (ATR Stops),183347.760,68200,115147.760,168.838,754.353,20700,3,474.447,1.604,349.772
1,signal_ema_price (ATR Stops),182828.962,68200,114628.962,168.078,260.002,3750,0,0.000,1.607,349.772
2,signal_macd_buy (ATR Stops),182750.388,68200,114550.388,167.962,181.428,4500,0,0.000,1.608,349.772
3,signal_ema_price_&_macd (ATR Stops),182602.864,68200,114402.864,167.746,33.905,300,0,0.000,1.608,349.772
4,signal_stochastic_buy (ATR Stops),182600.064,68200,114400.064,167.742,31.104,3150,0,0.000,1.607,349.772
5,signal_bollinger_buy (ATR Stops),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772
6,signal_macd_&_stochastic (ATR Stops),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772
7,signal_ema_price_&_stochastic (ATR Stops),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772
8,signal_ichimoku_kijun_cross_&_stochastic (ATR ...,182527.979,68200,114327.979,167.636,-40.981,1800,0,0.000,1.607,349.772

#### 1.4 Backtesting sin Stop Loss ni ATR

In [7]:
print(" Iniciando Evaluación  sin Stops ni ATR")
df_resultados_finales = evaluate_all_strategies(df, estrategias_a_probar, backtest_dca_plus_trading_NO_SL,params)

print("\n Tabla Comparativa de Estrategias sin Stop ")
display(df_resultados_finales)

 Iniciando Evaluación  sin Stops ni ATR
Evaluando: signal_ema_price...
Evaluando: signal_macd_buy...
Evaluando: signal_stochastic_buy...
Evaluando: signal_ichimoku_kijun_cross...
Evaluando: signal_bollinger_buy...
Evaluando: signal_macd_&_stochastic...
Evaluando: signal_ema_price_&_macd...
Evaluando: signal_ichimoku_kijun_cross_&_stochastic...
Evaluando: signal_ema_price_&_stochastic...

 Tabla Comparativa de Estrategias sin Stop

,Strategy,Final Portfolio Value,Total Contributions,Absolute Return,Percentage Return,Trading PnL,Trading Capital Used,Open Trades at End,Value of Open Trades,Sharpe Ratio,Total DCA Shares
0,signal_ichimoku_kijun_cross (No SL),184620.652,68200,116420.652,170.705,2044.031,17100,8,1207.662,1.604,349.772
1,signal_macd_buy (No SL),183060.866,68200,114860.866,168.418,499.262,4050,1,142.644,1.608,349.772
2,signal_ema_price (No SL),183024.755,68200,114824.755,168.365,457.743,3750,1,148.052,1.608,349.772
3,signal_stochastic_buy (No SL),182971.761,68200,114771.761,168.287,402.801,3150,0,0.000,1.608,349.772
4,signal_ichimoku_kijun_cross_&_stochastic (No SL),182801.578,68200,114601.578,168.038,232.618,1800,0,0.000,1.608,349.772
5,signal_ema_price_&_macd (No SL),182606.885,68200,114406.885,167.752,37.925,300,0,0.000,1.608,349.772
6,signal_bollinger_buy (No SL),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772
7,signal_macd_&_stochastic (No SL),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772
8,signal_ema_price_&_stochastic (No SL),182568.960,68200,114368.960,167.696,0.000,0,0,0.000,1.608,349.772

#### ESTRATEGIA SELF SUFFICIENT (NO DEFINITIVA)

In [8]:
# Deshabilitar gráficos
params['plot'] = False
params['initial_trading_cash']=10000

df_resultados_finales = evaluate_all_strategies(df, estrategias_a_probar, backtest_dca_self_sufficient, params)

print("\n Tabla Comparativa de Estrategias sin Stop ")
display(df_resultados_finales)

Evaluando: signal_ema_price...
Evaluando: signal_macd_buy...
Evaluando: signal_stochastic_buy...
Evaluando: signal_ichimoku_kijun_cross...
Evaluando: signal_bollinger_buy...
Evaluando: signal_macd_&_stochastic...
Evaluando: signal_ema_price_&_macd...
Evaluando: signal_ichimoku_kijun_cross_&_stochastic...
Evaluando: signal_ema_price_&_stochastic...

 Tabla Comparativa de Estrategias sin Stop

,Strategy,Final Portfolio Value,Total Contributions,Absolute Return,Percentage Return,Trading PnL,Trading Capital Used,Open Trades at End,Value of Open Trades,Sharpe Ratio,DCA Total Shares,DCA Shares Value
0,signal_macd_buy (Self-Sufficient),52426.327,20000,32426.327,162.132,19.288,150,0,0.000,0.693,100.956,52407.039
1,signal_bollinger_buy (Self-Sufficient),52407.039,20000,32407.039,162.035,0.000,0,0,0.000,0.693,100.956,52407.039
2,signal_macd_&_stochastic (Self-Sufficient),52407.039,20000,32407.039,162.035,0.000,0,0,0.000,0.693,100.956,52407.039
3,signal_ema_price_&_macd (Self-Sufficient),52407.039,20000,32407.039,162.035,0.000,0,0,0.000,0.693,100.956,52407.039
4,signal_ema_price_&_stochastic (Self-Sufficient),52407.039,20000,32407.039,162.035,0.000,0,0,0.000,0.693,100.956,52407.039
5,signal_ichimoku_kijun_cross (Self-Sufficient),52283.503,20000,32283.503,161.418,351.862,9450,2,317.953,0.695,100.006,51913.688
6,signal_ema_price (Self-Sufficient),52247.210,20000,32247.210,161.236,10.546,750,0,0.000,0.692,100.628,52236.664
7,signal_ichimoku_kijun_cross_&_stochastic (Self...,52141.148,20000,32141.148,160.706,21.916,600,0,0.000,0.691,100.402,52119.232
8,signal_stochastic_buy (Self-Sufficient),52133.188,20000,32133.188,160.666,13.955,750,0,0.000,0.691,100.402,52119.232